### ISSUE TITLE
[language-translator] Not Authorized from example project

### ISSUE THREAD

**Issue by hendrawd** [watson-developer-cloud/android-sdk#18]
`[language-translator]` from example project will throw
```
12-15 11:32:29.464 6619-6671/com.ibm.watson.developer_cloud.android.myapplication E/WatsonService: https://gateway.watsonplatform.net/language-translation/api/v2/translate, status: 401, error: Not Authorized
12-15 11:32:29.467 6619-6671/com.ibm.watson.developer_cloud.android.myapplication E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                                                    Process: com.ibm.watson.developer_cloud.android.myapplication, PID: 6619
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                                                     Caused by: com.ibm.watson.developer_cloud.service.UnauthorizedException: Unauthorized: Access is denied due to invalid credentials
                                                                                                        at com.ibm.watson.developer_cloud.service.WatsonService.execute(WatsonService.java:143)
                                                                                                        at com.ibm.watson.developer_cloud.service.WatsonService.executeRequest(WatsonService.java:183)
                                                                                                        at com.ibm.watson.developer_cloud.language_translation.v2.LanguageTranslation.translateRequest(LanguageTranslation.java:293)
                                                                                                        at com.ibm.watson.developer_cloud.language_translation.v2.LanguageTranslation.translate(LanguageTranslation.java:256)
                                                                                                        at com.ibm.watson.developer_cloud.android.myapplication.MainActivity$TranslationTask.doInBackground(MainActivity.java:332)
                                                                                                        at com.ibm.watson.developer_cloud.android.myapplication.MainActivity$TranslationTask.doInBackground(MainActivity.java:328)
                                                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                                        at java.lang.Thread.run(Thread.java:761) 
```
even i provided the correct credential from bluemix dashboard

### Steps to reproduce
Just use the example project, provide username and password, run

### Expected behavior
Not force closed and can translate the text i provided

### Actual behavior
Force closed and throw exception

### Android Phone
One Plus One(A001)

CyanogenMod version 14.1-20161123-NIGHTLY-bacon

Android version 7.1

### android-sdk version
Same with example project:

compileSdkVersion 23

buildToolsVersion "23.0.2"

minSdkVersion 9

targetSdkVersion 23

**Comment by germanattanasio** [comment]
Hey @hendrawd I think you are trying to use the `LanguageTranslator` service, but you are using `LanguageTranslation` in your code. Please check that because we change the service name recently.

**Comment by hendrawd** [comment]
@germanattanasio So how to use LanguageTranslation service from IBM Bluemix dashboard in [https://console.ng.bluemix.net/catalog/?category=services&taxonomyNavigation=services](https://console.ng.bluemix.net/catalog/?category=services&taxonomyNavigation=services)?
I can't seem to find `LanguageTranslation` service there, only `LanguageTranslator`

**Comment by germanattanasio** [comment]
You can't use `LanguageTranslation` that service was renamed to `LanguageTranslator`. Just use `LanguageTranslator`

**Comment by hendrawd** [comment]
@germanattanasio so this example project will not works right? Because it is used LanguageTranslation

**Comment by germanattanasio** [comment]
I just saw the example project and you are right. It won't work. You need to update the example to use the `LanguageTranslator` service. It should be easy because it's the exact same service as `LanguageTranslation` we just changed the name

**Comment by hendrawd** [comment]
thanks for the update, i will check it tomorrow and let you know the result
