### ISSUE TITLE
[speech-to-text] RunTimeException - MicrophoneCaptureThread.run

### ISSUE THREAD

**Issue by thibo73800** [watson-developer-cloud/android-sdk#22]
Project throw

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-306
                  Process: com.hommano.smojoapps, PID: 5928
                  java.lang.IllegalArgumentException: capacity < 0: -6
                      at java.nio.ByteBuffer.allocate(ByteBuffer.java:54)
                      at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.run(MicrophoneCaptureThread.java:87)
```
My application works fine on the simulator but not on my devices (Android 4.4.4, API 19)
Maybe the sdk does not support this API version ?

Here, is my gradle options

```
compileSdkVersion 23
buildToolsVersion 23.0.2
compileSdkVersion 23
minSdkVersion 15
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
compile 'com.ibm.watson.developer_cloud:java-sdk:3.5.3'
    compile 'com.ibm.watson.developer_cloud:android-sdk:0.2.1'

```
This error is raised when I try to call 

```java
capture = new MicrophoneInputStream(true);
```

My code : 
```java
package com.hommano.smojoapps;


import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;

import com.hommano.smojoapps.hoomano_sanbot_lib.HoomanoActivity;
import com.hommano.smojoapps.hoomano_sanbot_lib.SanbotSpeechToText;
import com.hommano.smojoapps.hoomano_sanbot_lib.WordSpoting;
import com.ibm.watson.developer_cloud.android.library.audio.MicrophoneInputStream;
import com.ibm.watson.developer_cloud.android.library.audio.StreamPlayer;
import com.ibm.watson.developer_cloud.android.library.camera.CameraHelper;
import com.ibm.watson.developer_cloud.android.library.camera.GalleryHelper;
import com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText;
import com.ibm.watson.developer_cloud.text_to_speech.v1.TextToSpeech;

public class Menu extends HoomanoActivity {

    private StreamPlayer player = new StreamPlayer();
    private CameraHelper cameraHelper;
    private GalleryHelper galleryHelper;
    private MicrophoneInputStream capture;
    private SpeechToText textService;


    View.OnClickListener onClick= new View.OnClickListener() {
        @Override
        public void onClick(View view) {

            switch (view.getId()){
                /*
                * Case for The main Menu
                * */
                case R.id.main_menu_b_home: // On Home Button
                    //sendCommandToMainService(103,0, "Home !");
                    Log.i("MainMenu", "Launch Home");
                    break;
                case R.id.main_menu_b_pd: // On product demonstrator button
                    //sendCommandToMainService(103,0, "Product demonstrator !");
                    Log.i("MainMenu", "Launch Product demonstrator");
                    break;
                case R.id.main_menu_ah: // On product demonstrator button
                    //sendCommandToMainService(103,0, "About Hoomano");
                    break;
                case R.id.main_menu_b_satisfaction: // On product demonstrator button
                    //sendCommandToMainService(103,0, "Satisfaction");
                    Log.i("MainMenu", "Launch Satisfaction");
                    break;
                case R.id.main_menu_b_entertainement: // On product demonstrator button
                    //sendCommandToMainService(103,0, "Entertainement");
                    Log.i("MainMenu", "Launch Entertainement");
                    break;
            }

            Log.i("MainMenu", "set listener");
        }
    };

    private SpeechToText initTextToSpeechService() {
        SpeechToText service = new SpeechToText();
        String username = "username";
        String password = "password";
        service.setUsernameAndPassword(username, password);
        service.setEndPoint("https://stream.watsonplatform.net/speech-to-text/api");
        return service;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_menu);

         /* Set all listener */
        Button main_menu_b_home = (Button) findViewById(R.id.main_menu_b_home);
        main_menu_b_home.setOnClickListener(onClick);

        Button main_menu_b_pd = (Button) findViewById(R.id.main_menu_b_pd);
        main_menu_b_pd.setOnClickListener(onClick);

        Button main_menu_ah = (Button) findViewById(R.id.main_menu_ah);
        main_menu_ah.setOnClickListener(onClick);

        Button main_menu_b_satisfaction = (Button) findViewById(R.id.main_menu_b_satisfaction);
        main_menu_b_satisfaction.setOnClickListener(onClick);

        Button main_menu_b_entertainement = (Button) findViewById(R.id.main_menu_b_entertainement);
        main_menu_b_entertainement.setOnClickListener(onClick);

        /*
        SanbotSpeechToText speech_to_text  = new SanbotSpeechToText();
        speech_to_text.listenKeyWords(new String[] {"Home", "Product Demonstrator", "About Hoomano", "Satisfaction", "Entertainment"}, new WordSpoting(){
            @Override
            public boolean onNewKeyWord(String keyword){
                sendCommandToMainService(103,0, keyword);
                return false;
            }
        });
        */

        cameraHelper = new CameraHelper(this);
        galleryHelper = new GalleryHelper(this);

        textService = initTextToSpeechService();

        try{
            capture = new MicrophoneInputStream(true);
        }
        catch (Exception e){
            System.out.println(e);
        }
    }


}
```

**Comment by JZHeadley** [comment]
I got the same error running it on a Samsung Galaxy S5 with api 21.  Did anyone ever figure out how to solve this error?

**Comment by ekeitho** [comment]
So MicrophoneInputStream uses MicrophoneCaptureThread and If you're getting java.lang.IllegalArgumentException: capacity < 0: -6. Then this is saying that 
`ByteBuffer bufferBytes = ByteBuffer.allocate(r * 2);`
is being called with a bad value, like a negative number. 

So it seems that **r** in this case would be -3. 

So going up near the start of MichrophoneCaptureThread: run() there is:
`int r = record.read(buffer, 0, buffer.length);`

since we know r is -3 and **record** is an AudioRecord object - this results to [AudioRecord.ERROR_INVALID_OPERATION](https://developer.android.com/reference/android/media/AudioRecord.html#ERROR_INVALID_OPERATION) 

then going into record.read implementation, I see the logic to throw this error

```
public int read(@NonNull byte[] audioData, int offsetInBytes, int sizeInBytes,
            @ReadMode int readMode) {
        if (mState != STATE_INITIALIZED  || mAudioFormat == AudioFormat.ENCODING_PCM_FLOAT) {
            // Denotes a failure due to the improper use of a method.
            return ERROR_INVALID_OPERATION;
        }
     \\...
         return native_read_in_short_array(audioData, offsetInShorts, sizeInShorts,
                readMode == READ_BLOCKING);
}
```

So either at the time of this call:
1. 'mState' is STATE_UNINITIALIZED 
2. or mAudioFormat is not ENCODING_PCM_FLOAT(this value was added in Lollipop (API 21))  
3. or native method is returning this value.

Since AudioRecord object is instantiated with - AudioFormat.ENCODING_PCM_16BIT, mAudioFormat will not be PCM_FLOAT. Thus it seems more likely AudioRecord resources had been released too early or it failed to initialize.

However, I am unable to reproduce this defect, so hopefully someone who can reproduce, can take a further look into this. 

If it failed to initilize then you should see an error log message like this:
**loge("Error code "+initResult+" when initializing native AudioRecord object.");**

**Comment by lpatino10** [comment]
I'll try and take a look at this in the next few days. Has anyone been able to reproduce this defect yet?

**Comment by LinkG** [comment]
I have been able to recreate this error...
All I did was set this example code:
`speechService.recognizeUsingWebSocket(new MicrophoneInputStream(),
getRecognizeOptions(), new BaseRecognizeCallback() {
  @Override
  public void onTranscription(SpeechResults speechResults){
    String text = speechResults.getResults().get(0).getAlternatives().get(0).getTranscript();
    System.out.println(text);
  }

  @Override
  public void onError(Exception e) {
  }

  @Override public void onDisconnected() {
  }

});`

to a button, the first time worked fine, but the second press gave me this error

**Comment by lpatino10** [comment]
Hey thanks for waiting. I just made a pull request that I think should clear up any recording issues. I didn't have any bugs in my testing. Be sure to follow the example code for using the microphone, as it's changed a bit, and feel free to open another issue if there are still problems.
