### ISSUE TITLE
Pick up photo from gallery for external sources ends up with an app crash

### ISSUE THREAD

**Issue by lgbaeza** [watson-developer-cloud/android-sdk#23]
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                  Process: com.ibm.watson.developer_cloud.android.myapplication, PID: 2902
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:325)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /external/images/media/34 (No such file or directory)
                      at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:182)
                      at com.ibm.watson.developer_cloud.android.myapplication.MainActivity$RecognitionTask.doInBackground(MainActivity.java:103)
                      at com.ibm.watson.developer_cloud.android.myapplication.MainActivity$RecognitionTask.doInBackground(MainActivity.java:96)
                      at android.os.AsyncTask$2.call(AsyncTask.java:305)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
                   Caused by: java.io.FileNotFoundException: /external/images/media/34 (No such file or directory)
                      at java.io.FileInputStream.open(Native Method)
                      at java.io.FileInputStream.<init>(FileInputStream.java:146)
                      at okio.Okio.source(Okio.java:168)
                      at okhttp3.RequestBody$3.writeTo(RequestBody.java:117)
                      at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:171)
                      at okhttp3.MultipartBody.writeTo(MultipartBody.java:113)
                      at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:756)
                      at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
                      at okhttp3.RealCall.getResponse(RealCall.java:244)
                      at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                      at okhttp3.RealCall.execute(RealCall.java:57)
                      at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:179)
                      at com.ibm.watson.developer_cloud.android.myapplication.MainActivity$RecognitionTask.doInBackground(MainActivity.java:103) 
                      at com.ibm.watson.developer_cloud.android.myapplication.MainActivity$RecognitionTask.doInBackground(MainActivity.java:96) 
                      at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
Disconnected from the target VM, address: 'localhost:8870', transport: 'socket'

**Comment by lgbaeza** [comment]
I found a possible solution. modify the GalleryHelper with the following code and update the minAPI version to 11.
[galleryHelper.java.txt](https://github.com/watson-developer-cloud/android-sdk/files/732925/galleryHelper.java.txt)
