### ISSUE TITLE
[speech-to-text] MicrophoneCaptureThread error

### ISSUE THREAD

**Issue by LinkG** [watson-developer-cloud/android-sdk#44]
- Steps to reproduce
Used example code for speech to text
- Expected behavior
It should accept the microphone input the second time
- Actual behavior
It crashes with the error:
`09-03 20:51:06.229 18825-19210/proj E/AudioRecord: start() status -38
09-03 20:51:06.229 18825-19210/proj E/AndroidRuntime: FATAL EXCEPTION: Thread-19856
                                                           Process: proj, PID: 18825
                                                           java.lang.IllegalArgumentException: capacity < 0: -6
                                                               at java.nio.ByteBuffer.allocate(ByteBuffer.java:54)
                                                               at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.run(MicrophoneCaptureThread.java:90)`
- [ Nexus 5 ] Android Phone / Simulator
- [ 24 ] android-sdk version

**Comment by LinkG** [comment]
I am extremely sorry for opening this issue, if anyone had the same issue,
close the input stream in the onDisconnect method
