### ISSUE TITLE
Streamplayer is not getting initialised. Please help.

### ISSUE THREAD

**Issue by lavanya-lnt** [watson-developer-cloud/android-sdk#47]
I find the following issue after the streamplayer is called for 5-6 times. First few times it works fine but later it throws the following error.

```
12-11 11:06:09.076 28550-4066/com.trail E/AudioTrack: AudioFlinger could not create track, status: -12
12-11 11:06:09.076 28550-4066/com.trail E/AudioTrack-JNI: Error -12 initializing AudioTrack
12-11 11:06:09.077 28550-4066/com.trail E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
12-11 11:06:09.079 28550-4066/com.trail E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
                                                                   Process: com.trail, PID: 28550
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
                                                                       at android.media.AudioTrack.play(AudioTrack.java:1742)
                                                                       at com.ibm.watson.developer_cloud.android.library.audio.StreamPlayer.initPlayer(StreamPlayer.java:96)
                                                                       at com.ibm.watson.developer_cloud.android.library.audio.StreamPlayer.playStream(StreamPlayer.java:65)
```

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps. Check the CONTRIBUTING.md for an example.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
