### ISSUE TITLE
Error on microphone button click

### ISSUE THREAD

**Issue by eumagnun** [watson-developer-cloud/android-sdk#48]
When i click on microphone button the app stop.

The error bellow is showed in LogCat console:
```

E/AndroidRuntime: FATAL EXCEPTION: Thread-1445
                  Process: br.com.pegasuswe.projeto_modelo_watson, PID: 9115
                  java.lang.NoClassDefFoundError: com.ibm.watson.developer_cloud.android.library.audio.opus.JNAOpus
                      at com.ibm.watson.developer_cloud.android.library.audio.opus.OggOpusEnc.initEncoder(OggOpusEnc.java:65)
                      at com.ibm.watson.developer_cloud.android.library.audio.opus.OggOpusEnc.<init>(OggOpusEnc.java:52)
                      at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.run(MicrophoneCaptureThread.java:68)
D/OpenGLRenderer: endAllStagingAnimators on 0xed1b1d8
0 (RippleDrawable) with handle 0xe90fe860


```

All another functions are OK.

**Comment by VidyasagarMSC** [comment]
+1
Seeing a crash while calling `speechService.recognizeUsingWebSocket` on microphone button click.

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps. Check the CONTRIBUTING.md for an example.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
