### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by venumanas87** [watson-developer-cloud/android-sdk#89]
The code throws follwoing error when the activity starts.

Fatal Exception: java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/com.quizo-C1Fi6ybosViFkZ8r4_0jBg==/base.apk!classes3.dex)
       at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:111)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:161)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
       at com.ibm.watson.developer_cloud.service.security.IamTokenManager.callIamApi(IamTokenManager.java:180)
       at com.ibm.watson.developer_cloud.service.security.IamTokenManager.requestToken(IamTokenManager.java:101)
       at com.ibm.watson.developer_cloud.service.security.IamTokenManager.getToken(IamTokenManager.java:71)
       at com.ibm.watson.developer_cloud.service.WatsonService.setAuthentication(WatsonService.java:354)
       at com.ibm.watson.developer_cloud.service.WatsonService.createCall(WatsonService.java:190)
       at com.ibm.watson.developer_cloud.service.WatsonService.createServiceCall(WatsonService.java:224)
       at com.ibm.watson.developer_cloud.assistant.v1.Assistant.message(Assistant.java:192)
       at com.quizo.bot$3.run(bot.java:154)
       at java.lang.Thread.run(Thread.java:764)

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.
