### ISSUE TITLE
Issue in speech to text 

### ISSUE THREAD

**Issue by premchand-algo** [watson-developer-cloud/android-sdk#90]
I am getting this issue in speech to text android sample code.

FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.ibm.watson.developer_cloud.android.myapplication, PID: 13486
    java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1291)
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:466)
        at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.end(MicrophoneCaptureThread.java:138)
        at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneInputStream.close(MicrophoneInputStream.java:109)
        at com.ibm.watson.developer_cloud.android.myapplication.StartReadingActivity$MicrophoneRecognizeDelegate.onError(StartReadingActivity.java:123)
        at com.ibm.watson.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.onFailure(SpeechToTextWebSocketListener.java:108)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by germanattanasio** [comment]
@premchand-algo can you specify what are the steps you took to run the sample app and when you are seeing the error?

**Comment by premchand-algo** [comment]
This sample is working fine 10 days ago, I have nothing to change in it. And now it gives this issue at onError method line **capture.close()** of RecognizeCallback.

private class MicrophoneRecognizeDelegate extends BaseRecognizeCallback implements RecognizeCallback {
        @Override
        public void onTranscription(SpeechRecognitionResults speechResults) {
            Log.e("Speech Results", speechResults.toString());
            if (speechResults.getResults() != null && !speechResults.getResults().isEmpty()) {
                String text = speechResults.getResults().get(0).getAlternatives().get(0).getTranscript();
                Log.e("Speech text", text);
            }
        }

        @Override
        public void onError(Exception e) {
            try {
                // This is critical to avoid hangs
                // (see https://github.com/watson-developer-cloud/android-sdk/issues/59)
                **capture.close();**
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            showError(e);
            enableMicButton();
        } 

**Note: While the exception is as followed after it the above error is coming**

java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
W:     at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
W:     at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
W:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
W:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W:     at java.lang.Thread.run(Thread.java:919)

.

**Comment by germanattanasio** [comment]
So without changing any code you started to see a problem. I think that could be a service issue not an issue in this SDK.

**Comment by premchand-algo** [comment]
Can you help me, why i am getting the following exception?

java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
W: at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
W: at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
W: at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
W: at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W: at java.lang.Thread.run(Thread.java:919)
