### ISSUE TITLE
Getting exception with library-release.aar file 

### ISSUE THREAD

**Issue by premchand-algo** [watson-developer-cloud/android-sdk#91]
FATAL EXCEPTION: Thread-3
    Process: com.book.reading, PID: 12353
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sun/jna/Library;
        at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.run(MicrophoneCaptureThread.java:72)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sun.jna.Library" on path: DexPathList[[zip file "/data/app/com.book.reading-dHpwYZuOlQuiIAAnLaOW-Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.book.reading-dHpwYZuOlQuiIAAnLaOW-Q==/lib/arm64, /data/app/com.book.reading-dHpwYZuOlQuiIAAnLaOW-Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.run(MicrophoneCaptureThread.java:72)

**Comment by germanattanasio** [comment]
I think the aar is missing a few classes. I will look into it once I get some time, maybe next week
