### ISSUE TITLE
Issue while reading text

### ISSUE THREAD

**Issue by premchand-algo** [watson-developer-cloud/android-sdk#93]
Hi, I am getting this issue most of the time and application is going crash randomly.

 FATAL EXCEPTION: AudioToWebSocketThread
    java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1291)
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:466)
        at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneCaptureThread.end(MicrophoneCaptureThread.java:138)
        at com.ibm.watson.developer_cloud.android.library.audio.MicrophoneInputStream.close(MicrophoneInputStream.java:109)
        at com.ibm.watson.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.sendInputStream(SpeechToTextWebSocketListener.java:213)
        at com.ibm.watson.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.access$100(SpeechToTextWebSocketListener.java:42)
        at com.ibm.watson.speech_to_text.v1.websocket.SpeechToTextWebSocketListener$1.run(SpeechToTextWebSocketListener.java:168)

**Comment by kevinkowa** [comment]
Try it out with the latest version of the SDK and let me know if it works fine on your end!
